### ISSUE TITLE
error when runing get_funguild_db()

### ISSUE THREAD

**Issue by mrgambero** [brendanf/FUNGuildR#5]
Hello,
I am trying to use FUNguildR,
but I get the following error, with both the function
get_funguild_db() and funguild_assign
for example:
> get_funguild_db()
Error: lexical error: invalid char in json text.
                                       </body>
                     (right here) ------^

help appreciated!!
Thanks for your work!!!

Gabri

**Comment by brendanf** [comment]
Hi Gabri,
I can confirm this issue.  It appears that there is an issue with the FUNGuild server, and it is returning an empty database.  I'll contact people closer to the database maintenance and see if I can figure out when it will be working again.
Brendan

**Comment by brendanf** [comment]
@mrgambero The server seems to be back up and working for me now.  Give it another try, hopefully it will work for you too.

**Comment by mrgambero** [comment]
Thanks Brendan! it works now! I think it was not able to download the database before
